# ---- Etapa de build ----
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY AuthService.sln ./
COPY src/AuthService.Domain/ src/AuthService.Domain/
COPY src/AuthService.Persistence/ src/AuthService.Persistence/
COPY src/AuthService.Application/ src/AuthService.Application/
COPY src/AuthService.Api/ src/AuthService.Api/

RUN dotnet restore AuthService.sln
RUN dotnet publish src/AuthService.Api/AuthService.Api.csproj \
    -c Release \
    -o /app/publish \
    --no-restore

# ---- Etapa de runtime ----
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app

COPY --from=build /app/publish .

ENV ASPNETCORE_ENVIRONMENT=Production
ENV ASPNETCORE_URLS=http://+:3000
ENV DOTNET_RUNNING_IN_CONTAINER=true

EXPOSE 3000

ENTRYPOINT ["dotnet", "AuthService.Api.dll"]